create table users
(
    user_id     integer generated by default as identity
        primary key,
    name        varchar(15) default 'NoName'::character varying not null,
    email       varchar(40)                                     not null
        constraint e
            unique,
    role        varchar(10) default 'normal'::character varying not null,
    password    varchar(32) default md5('123456'::text)         not null,
    create_time time        default now()                       not null,
    update_time time        default now()                       not null
);

comment on column users.user_id is '用户 id';

comment on column users.name is '用户名';

comment on column users.email is '邮箱地址';

comment on column users.role is '角色';

comment on column users.password is '用户密码';

comment on column users.create_time is '创建时间';

alter table users
    owner to postgres;

