// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: YachiyoCuo2026.sql

package db

import (
	"context"
)

const createScore = `-- name: CreateScore :exec
insert into "YachiyoCup2026"(
id,
score
) values(
    $1,$2
)
`

type CreateScoreParams struct {
	ID    int32
	Score int32
}

func (q *Queries) CreateScore(ctx context.Context, arg CreateScoreParams) error {
	_, err := q.db.ExecContext(ctx, createScore, arg.ID, arg.Score)
	return err
}

const getId = `-- name: GetId :one
select id from "YachiyoCup2026"
where id  = $1 limit 1
`

func (q *Queries) GetId(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, getId, id)
	err := row.Scan(&id)
	return id, err
}

const getScore = `-- name: GetScore :one
select score from "YachiyoCup2026"
where id  = $1 limit 1
`

func (q *Queries) GetScore(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, getScore, id)
	var score int32
	err := row.Scan(&score)
	return score, err
}

const updataScore = `-- name: UpdataScore :exec
update "YachiyoCup2026"
set score = $2
where id = $1
`

type UpdataScoreParams struct {
	ID    int32
	Score int32
}

func (q *Queries) UpdataScore(ctx context.Context, arg UpdataScoreParams) error {
	_, err := q.db.ExecContext(ctx, updataScore, arg.ID, arg.Score)
	return err
}
