server:
  port: 8972
  tomcat:
      connection-timeout: 3600000ms  # 连接超时 1小时
      max-http-response-header-size: 8KB
  max-http-request-header-size: 8KB

spring:
  application:
    name: file-service # 应用名称


  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848   # Nacos 注册中心地址
        namespace: public                # 命名空间ID（非名称），用于环境隔离
        username: nacos             # 必须正确！默认是 nacos
        password: KaguyaIrohaForever           # 必须正确！默认是 nacos
        group: DEFAULT_GROUP
      config:
        server-addr: 127.0.0.1:8848   # Nacos 配置中心地址
        namespace: public
        username: nacos             # 必须正确！默认是 nacos
        password: KaguyaIrohaForever           # 必须正确！默认是 nacos
        group: DEFAULT_GROUP
        file-extension: yaml          # 配置文件格式
        refresh-enabled: true         # 启用动态刷新
  config:
    import: nacos:${spring.application.name}

  profiles:
    include: secret
  mvc:
    async:
      request-timeout: 3600000s

  minio:
    endpoint: http://127.0.0.1:9000
    access-key: ${minio.accessKey}
    secret-key: ${minio.secretKey}
