# 编译阶段
FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 go build -o main main.go

# 运行阶段（极小体积）
FROM alpine:latest
WORKDIR /app


COPY --from=builder /app/main .
COPY app.env .

EXPOSE 8989
CMD ["/app/main"]